require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonksController do

  # This should return the minimal set of attributes required to create a valid
  # Monk. As you add validations to Monk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cert_no" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all monks as @monks" do
      monk = Monk.create! valid_attributes
      get :index, {}, valid_session
      assigns(:monks).should eq([monk])
    end
  end

  describe "GET show" do
    it "assigns the requested monk as @monk" do
      monk = Monk.create! valid_attributes
      get :show, {:id => monk.to_param}, valid_session
      assigns(:monk).should eq(monk)
    end
  end

  describe "GET new" do
    it "assigns a new monk as @monk" do
      get :new, {}, valid_session
      assigns(:monk).should be_a_new(Monk)
    end
  end

  describe "GET edit" do
    it "assigns the requested monk as @monk" do
      monk = Monk.create! valid_attributes
      get :edit, {:id => monk.to_param}, valid_session
      assigns(:monk).should eq(monk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Monk" do
        expect {
          post :create, {:monk => valid_attributes}, valid_session
        }.to change(Monk, :count).by(1)
      end

      it "assigns a newly created monk as @monk" do
        post :create, {:monk => valid_attributes}, valid_session
        assigns(:monk).should be_a(Monk)
        assigns(:monk).should be_persisted
      end

      it "redirects to the created monk" do
        post :create, {:monk => valid_attributes}, valid_session
        response.should redirect_to(Monk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monk as @monk" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monk.any_instance.stub(:save).and_return(false)
        post :create, {:monk => { "cert_no" => "invalid value" }}, valid_session
        assigns(:monk).should be_a_new(Monk)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monk.any_instance.stub(:save).and_return(false)
        post :create, {:monk => { "cert_no" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monk" do
        monk = Monk.create! valid_attributes
        # Assuming there are no other monks in the database, this
        # specifies that the Monk created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Monk.any_instance.should_receive(:update).with({ "cert_no" => "1" })
        put :update, {:id => monk.to_param, :monk => { "cert_no" => "1" }}, valid_session
      end

      it "assigns the requested monk as @monk" do
        monk = Monk.create! valid_attributes
        put :update, {:id => monk.to_param, :monk => valid_attributes}, valid_session
        assigns(:monk).should eq(monk)
      end

      it "redirects to the monk" do
        monk = Monk.create! valid_attributes
        put :update, {:id => monk.to_param, :monk => valid_attributes}, valid_session
        response.should redirect_to(monk)
      end
    end

    describe "with invalid params" do
      it "assigns the monk as @monk" do
        monk = Monk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monk.any_instance.stub(:save).and_return(false)
        put :update, {:id => monk.to_param, :monk => { "cert_no" => "invalid value" }}, valid_session
        assigns(:monk).should eq(monk)
      end

      it "re-renders the 'edit' template" do
        monk = Monk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monk.any_instance.stub(:save).and_return(false)
        put :update, {:id => monk.to_param, :monk => { "cert_no" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monk" do
      monk = Monk.create! valid_attributes
      expect {
        delete :destroy, {:id => monk.to_param}, valid_session
      }.to change(Monk, :count).by(-1)
    end

    it "redirects to the monks list" do
      monk = Monk.create! valid_attributes
      delete :destroy, {:id => monk.to_param}, valid_session
      response.should redirect_to(monks_url)
    end
  end

end
